{% set name = "tabascal" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: |
    python -m pip install . --no-deps --prefix=$PREFIX -vv

requirements:
  host:
    - python >=3.10,<3.13
    - pip
    - setuptools >=64

  run:
    - python >=3.10,<3.13
    - jax
    - xarray
    - zarr <3.0.0
    - scipy
    - tqdm
    - pandas
    - matplotlib
    - astropy
    - requests
    - numpy <2.0.0
    - dask <=2024.10.0
    - dask-ms >=0.2.21
    - pyyaml
    - skyfield

about:
  home: https://github.com/chrisfinlay/tabascal
  summary: "Trajectory based RFI subtraction and calibration using Bayesian methods for radio interferometric data."
  license: LicenseRef-CUSTOM
  license_file: LICENSE
