name: Build conda package

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-variant: Mambaforge
          python-version: "3.9"

      - name: Install conda-build
        run: conda install conda-build -y
      
      - name: Build the conda package
        run: conda build recipe

      - name: Test the built package
        run: |
          conda create -n test-env --use-local tabascal -y
          conda run -n test-env tabascal --help