name: Build conda package

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          miniforge-variant: Miniforge3
          python-version: "3.9"

      - name: Install conda-build
        run: conda install conda-build -y
      
      - name: Build the conda package
        run: conda build recipe
